/* =========================================================
   DigiYar V5.1 — Main Application
   Live retrieval + product cards
   ========================================================= */
(function () {
  "use strict";
  function $(id){return document.getElementById(id);}
  function escapeHTML(value){return String(value??"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c];});}
  function toArray(value){return Array.isArray(value)?value:[];}
  function getProductImage(product){return product&&(product.image||product.imageUrl||product.thumbnail||product.thumbnailUrl||product.photo||"");}
  function priorityLabel(index){return ["اولویت اول","اولویت دوم","اولویت سوم"][index]||"اولویت "+(index+1);}
  function renderPlatforms(){const container=$("platforms");if(!container||!window.DigiYarPlatforms)return;container.innerHTML=DigiYarPlatforms.map(function(platform){return '<a class="platform" href="'+escapeHTML(platform.url)+'" target="_blank" rel="noopener noreferrer"><div class="platform-main"><div class="platform-logo"><img src="'+escapeHTML(platform.logo)+'" alt="'+escapeHTML(platform.name)+'" loading="lazy"></div><span class="platform-name">'+escapeHTML(platform.name)+'</span><span class="platform-tag">'+escapeHTML(platform.tag)+'</span></div><span class="platform-btn">ورود به فروشگاه</span></a>';}).join("");}
  let v51Ready=null;
  function loadScript(path){return new Promise(function(resolve,reject){if(document.querySelector('script[src$="/'+path+'"]')){resolve();return;}const s=document.createElement('script');s.src=new URL(path,document.baseURI).href;s.async=false;s.onload=resolve;s.onerror=function(){reject(Error('Failed to load '+path));};document.head.appendChild(s);});}
  async function ensureV51Live(){if(v51Ready)return v51Ready;v51Ready=(async function(){if(!window.DigiYarV5CatalogAdapter)await loadScript('js/v5-catalog-adapter.js');if(!window.DigiYarV5PriceEngine)await loadScript('js/v5-price-engine.js');if(!window.DigiYarV5CandidateRetrieval)await loadScript('js/v5-candidate-retrieval.js');if(!window.DigiYarOfferAffiliate)await loadScript('js/v5-offer-affiliate-engine.js');if(!window.DigiyarProductRetrievalIntegration)await loadScript('js/product-retrieval-integration.js');})().catch(function(error){v51Ready=null;throw error;});return v51Ready;}
  async function getRecommendations(need){try{await ensureV51Live();const live=window.DigiyarProductRetrievalIntegration;if(live&&typeof live.retrieve==='function'){const result=await live.retrieve(need,{limit:3,candidateLimit:10,resolverTimeout:10000});if(result&&Array.isArray(result.products)&&result.products.length)return result.products;}}catch(error){console.warn("DigiYar V5.1 Live Retrieval:",error);}const engine=window.DigiYarSmartRecommendation||window.DigiYarSmartRecommendationEngine;if(!engine||typeof engine.recommend!=="function")return[];try{const result=await engine.recommend(need,{limit:3});return result&&Array.isArray(result.recommendations)?result.recommendations:[];}catch(error){console.warn("DigiYar Recommendation:",error);return[];}}
  function renderRecommendationCard(product,index){const image=getProductImage(product),features=toArray(product.features);const price=product.price!=null&&Number(product.price)>0?new Intl.NumberFormat("fa-IR").format(product.price)+" تومان":"قیمت نامشخص";const url=product.affiliateUrl||product.productUrl||product.url||"#";return '<article class="recommendation" data-rank="'+escapeHTML(index+1)+'"><div class="recommendation-rank">'+escapeHTML(priorityLabel(index))+'</div>'+(image?'<div class="recommendation-product-image"><img src="'+escapeHTML(image)+'" alt="'+escapeHTML(product.name||"محصول پیشنهادی")+'" loading="lazy">':'')+'<h3>'+escapeHTML(product.name||"محصول پیشنهادی")+'</h3><p class="recommendation-price">'+escapeHTML(price)+'</p>'+(features.length?'<p class="recommendation-features">'+escapeHTML(features.join("، "))+'</p>':'')+'<a class="recommendation-link" href="'+escapeHTML(url)+'" target="_blank" rel="noopener noreferrer">مشاهده کالا</a></article>';}
  function fillForm(profile){if(!profile)return;const d=profile.declared||{};if($("category"))$("category").value=d.category||"general";if($("budgetMax"))$("budgetMax").value=d.budget&&d.budget.max?d.budget.max:"";if($("priorities"))$("priorities").value=(d.priorities||[]).join("، ");if($("usage"))$("usage").value=d.usage||"";if($("requirements"))$("requirements").value=(d.requirements||[]).join("، ");if($("constraints"))$("constraints").value=(d.constraints||[]).join("، ");}
  async function renderProfile(profile){const summary=$("needSummary"),box=$("recommendations"),hint=$("resultHint");if(!summary||!box||!hint)return;summary.className="need-summary empty";summary.textContent="";if(!profile){box.innerHTML="";hint.textContent="برای شروع اطلاعات خریدت رو وارد کن.";return;}if(!window.DigiYarNeedEngine){hint.textContent="موتور تحلیل نیاز در دسترس نیست.";return;}let need;try{need=window.DigiYarNeedEngine.buildNeedFromProfile(profile);}catch(error){console.error("DigiYar Need Engine:",error);hint.textContent="خطا در ساخت نیاز خرید.";return;}if(!need)return;hint.textContent="در حال پیدا کردن کالاهای مناسب...";box.innerHTML='<div class="recommendation-loading">در حال جستجوی کالاهای واقعی...</div>';const recommendations=await getRecommendations(need);if(!recommendations.length){box.innerHTML='<div class="need-summary">برای این نیاز هنوز پیشنهاد مناسبی پیدا نشد.</div>';hint.textContent="اطلاعات بیشتری وارد کن تا پیشنهادهای دقیق‌تری ساخته شود.";return;}box.innerHTML=recommendations.map(renderRecommendationCard).join("");hint.textContent="بر اساس اولویت‌های انتخابی تو به ترتیب زیر پیشنهاد میشن";}
  const profileForm=$("profileForm");if(profileForm)profileForm.addEventListener("submit",async function(event){event.preventDefault();if(!window.DigiYarUserProfile)return;try{const profile=window.DigiYarUserProfile.normalize({category:$("category")?$("category").value:"",budgetMax:$("budgetMax")?$("budgetMax").value:"",priorities:$("priorities")?$("priorities").value:"",usage:$("usage")?$("usage").value:"",requirements:$("requirements")?$("requirements").value:"",constraints:$("constraints")?$("constraints").value:""});window.DigiYarUserProfile.save(profile);await renderProfile(profile);const resultSection=$("resultSection");if(resultSection)resultSection.scrollIntoView({behavior:"smooth",block:"start"});}catch(error){console.error("DigiYar Profile:",error);}});
  const reset=$("resetProfile");if(reset)reset.addEventListener("click",function(){if(window.DigiYarUserProfile)window.DigiYarUserProfile.clear();if($("profileForm"))$("profileForm").reset();renderProfile(null);});
  let deferredInstallPrompt=null;let installPromptShown=false;let installPromptDismissed=false;let installPromptTimer=null;let installPromptDelayTimer=null;
  const installPrompt=$("installPrompt"),installBtn=$("installBtn"),installDismiss=$("installDismiss");
  function hideInstallPrompt(){if(!installPrompt)return;installPrompt.classList.remove("show");window.setTimeout(function(){installPrompt.classList.add("hidden");},600);}
  function showInstallPrompt(){if(installPromptShown||installPromptDismissed||!deferredInstallPrompt||!installPrompt)return;installPromptShown=true;installPrompt.classList.remove("hidden");requestAnimationFrame(function(){installPrompt.classList.add("show");});window.clearTimeout(installPromptTimer);installPromptTimer=window.setTimeout(hideInstallPrompt,9000);}
  /* Splash is 3s. Install notification must appear exactly 5s after splash ends. */
  const installEligibleAt=Date.now()+8000;
  window.addEventListener("beforeinstallprompt",function(event){event.preventDefault();deferredInstallPrompt=event;window.clearTimeout(installPromptDelayTimer);installPromptDelayTimer=window.setTimeout(showInstallPrompt,Math.max(0,installEligibleAt-Date.now()));});
  if(installBtn)installBtn.addEventListener("click",async function(){if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice;}catch(e){}deferredInstallPrompt=null;window.clearTimeout(installPromptTimer);hideInstallPrompt();});
  if(installDismiss)installDismiss.addEventListener("click",function(){installPromptDismissed=true;window.clearTimeout(installPromptTimer);window.clearTimeout(installPromptDelayTimer);hideInstallPrompt();});
  renderPlatforms();let savedProfile=null;if(window.DigiYarUserProfile){try{savedProfile=window.DigiYarUserProfile.getProfile();}catch(error){savedProfile=null;}}fillForm(savedProfile);renderProfile(savedProfile);
})();