/* =========================================================
   DigiYar V5.1 — Main Application
   Live retrieval + product cards
   ========================================================= */
(function () {
  "use strict";
  function $(id){return document.getElementById(id);}
  function escapeHTML(value){return String(value??"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]||c;});}
  function toArray(value){return Array.isArray(value)?value:[];}
  function getProductImage(product){return product&&(product.image||product.imageUrl||product.thumbnail||product.thumbnailUrl||product.photo||"");}
  function priorityLabel(index){return ["اولویت اول","اولویت دوم","اولویت سوم"][index]||"اولویت "+(index+1);}
  const selectedStoreLogos={
    neshatrokh:'assets/store-logos/%D9%86%D8%B4%D8%A7%D8%B7%20%D8%B1%D8%AE.webp',
    eseminar:'assets/store-logos/%D8%A7%DB%8C%D8%B3%D9%85%DB%8C%D9%86%D8%A7%D8%B1.webp',
    safarme:'assets/store-logos/%D8%B3%D9%81%D8%B1%20%D9%85%DB%8C.webp',
    berozkala:'assets/store-logos/%D8%A8%D9%87%20%D8%B1%D9%88%D8%B2%20%DA%A9%D8%A7%D9%84%D8%A7.webp',
    maktabkhooneh:'assets/store-logos/%D9%85%DA%A9%D8%AA%D8%A8%20%D8%AE%D9%88%D9%86%D9%87.webp',
    'daroo-online':'assets/store-logos/%D8%AF%D8%A7%D8%B1%D9%88%D8%AE%D8%A7%D9%86%D9%87%20%D8%A2%D9%86%D9%84%D8%A7%DB%8C%D9%86.webp',
    gooshishop:'assets/store-logos/%DA%AF%D9%88%D8%B4%DB%8C%20%D8%B4%D8%A7%D9%BE.webp',
    karnameh:'assets/store-logos/%DA%A9%D8%A7%D8%B1%D9%86%D8%A7%D9%85%D9%87.webp',
    technolife:'assets/store-logos/%D8%AA%DA%A9%D9%86%D9%88%D9%84%D8%A7%DB%8C%D9%81.webp',
    solokala:'assets/store-logos/%D8%B3%D9%88%D9%84%D9%88%20%DA%A9%D8%A7%D9%84%D8%A7.webp'
  };
  const newStoreLogoIds=new Set(['khanoumi','banimode','modiseh','esam','pinket','darukade','darmankala','digido','janebi','takhfifan','shab','neshatrokh','mosbatesabz','shavaz','jeanswest','eseminar','safarme','berozkala','maktabkhooneh','daroo-online','gooshishop','karnameh','technolife','solokala']);
  function syncSelectedStoreData(){const stores=window.DigiYarPopularAffiliateStores;if(!stores)return;stores.forEach(function(store){if(selectedStoreLogos[store.id])store.logo=selectedStoreLogos[store.id];if(store.id==='daroo-online')store.url='https://DarookhaneOnline.com/';});}
  function syncHeaderStoreLinks(){document.querySelectorAll('[data-store]').forEach(function(el){const id=el.getAttribute('data-store');if(id==='daroo-online'&&el.tagName==='A')el.href='https://DarookhaneOnline.com/';});}
  function renderStoreSelect(){const select=$("storeSelect"),stores=window.DigiYarPopularAffiliateStores;if(!select||!Array.isArray(stores))return;const current=select.value;const seen=new Set();select.innerHTML='<option value="all">همه فروشگاه‌های متصل</option>';stores.forEach(function(store){if(!store||!store.id||!store.name||seen.has(store.id))return;seen.add(store.id);const option=document.createElement('option');option.value=store.id;option.textContent=store.name;select.appendChild(option);});if(seen.has(current)||current==='all')select.value=current;}
  function syncPopularGridHeight(){const card=document.querySelector('.v5-popular-card'),grid=$("platforms");if(!card||!grid)return;if(card.classList.contains('is-open')){grid.style.maxHeight='none';grid.style.height='auto';}else{grid.style.maxHeight='0px';grid.style.height='0px';}}
  function renderPlatforms(){const container=$("platforms");syncSelectedStoreData();const stores=window.DigiYarPopularAffiliateStores||window.DigiYarPlatforms;if(!container||!stores)return;container.innerHTML=stores.map(function(platform){const logo=platform.logo||"";const mark=platform.mark||platform.name.slice(0,2);const logoClass=newStoreLogoIds.has(platform.id)?" platform-logo-new":"";return '<a class="platform" href="'+escapeHTML(platform.url)+'" target="_blank" rel="noopener noreferrer" data-store="'+escapeHTML(platform.id||"")+'" aria-label="ورود به '+escapeHTML(platform.name)+'"><div class="platform-main"><span class="platform-logo'+logoClass+'" aria-hidden="true">'+(logo?'<img src="'+escapeHTML(logo)+'" alt="" loading="lazy" decoding="async" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'flex\'">':'')+'<span class="platform-mark" style="display:'+(logo?'none':'flex')+'">'+escapeHTML(mark)+'</span></span><span class="platform-name">'+escapeHTML(platform.name)+'</span><span class="platform-tag">'+escapeHTML(platform.tag||platform.tagline||"")+'</span></div><span class="platform-btn">ورود به فروشگاه</span></a>';}).join("");ensurePopularToggle();syncHeaderStoreLinks();syncPopularGridHeight();}
  function ensurePopularToggle(){const card=document.querySelector(".v5-popular-card");const grid=$("platforms");if(!card||!grid)return;let toggle=card.querySelector(".v5-popular-toggle");if(!toggle){toggle=document.createElement("button");toggle.type="button";toggle.className="v5-popular-toggle";toggle.setAttribute("aria-expanded","true");toggle.setAttribute("aria-label","بستن فروشگاه‌های محبوب");toggle.innerHTML='<span class="v5-popular-toggle-icon" aria-hidden="true"><i>‹</i><i>›</i></span>';grid.insertAdjacentElement("afterend",toggle);card.classList.add('is-open');toggle.addEventListener("click",function(){const open=card.classList.toggle("is-open");toggle.setAttribute("aria-expanded",String(open));toggle.setAttribute("aria-label",open?"بستن فروشگاه‌های محبوب":"نمایش فروشگاه‌های محبوب");syncPopularGridHeight();});}else{card.classList.add('is-open');toggle.setAttribute("aria-expanded","true");syncPopularGridHeight();}}
  let v51Ready=null;
  function loadScript(path){return new Promise(function(resolve,reject){if(document.querySelector('script[src$="/'+path+'"]')){resolve();return;}const s=document.createElement('script');s.src=new URL(path,document.baseURI).href;s.async=false;s.onload=resolve;s.onerror=function(){reject(Error('Failed to load '+path));};document.head.appendChild(s);});}
  async function ensureV51Live(){if(v51Ready)return v51Ready;v51Ready=(async function(){if(!window.DigiYarV5CatalogAdapter)await loadScript('js/v5-catalog-adapter.js');if(!window.DigiYarV5PriceEngine)await loadScript('js/v5-price-engine.js');if(!window.DigiYarV5CandidateRetrieval)await loadScript('js/v5-candidate-retrieval.js');if(!window.DigiYarOfferAffiliate)await loadScript('js/v5-offer-affiliate-engine.js');if(!window.DigiyarProductRetrievalIntegration)await loadScript('js/product-retrieval-integration.js');})().catch(function(error){v51Ready=null;throw error;});return v51Ready;}
  async function getRecommendations(need){try{await ensureV51Live();const live=window.DigiyarProductRetrievalIntegration;if(live&&typeof live.retrieve==='function'){const result=await live.retrieve(need,{limit:3,candidateLimit:10,resolverTimeout:10000});if(result&&Array.isArray(result.products)&&result.products.length)return result.products;}}catch(error){console.warn("DigiYar V5.1 Live Retrieval:",error);}const engine=window.DigiYarSmartRecommendation||window.DigiYarSmartRecommendationEngine;if(!engine||typeof engine.recommend!=="function")return[];try{const result=await engine.recommend(need,{limit:3});return result&&Array.isArray(result.recommendations)?result.recommendations:[];}catch(error){console.warn("DigiYar Recommendation:",error);return[];}}
  function renderRecommendationCard(product,index){const image=getProductImage(product),features=toArray(product.features);const price=product.price!=null&&Number(product.price)>0?new Intl.NumberFormat("fa-IR").format(product.price)+" تومان":"قیمت نامشخص";const url=product.affiliateUrl||product.productUrl||product.url||"#";return '<article class="recommendation" data-rank="'+escapeHTML(index+1)+'"><div class="recommendation-rank">'+escapeHTML(priorityLabel(index))+'</div>'+(image?'<div class="recommendation-product-image"><img src="'+escapeHTML(image)+'" alt="'+escapeHTML(product.name||"محصول پیشنهادی")+'" loading="lazy">':'')+'<h3>'+escapeHTML(product.name||"محصول پیشنهادی")+'</h3><p class="recommendation-price">'+escapeHTML(price)+"</p>"+(features.length?'<p class="recommendation-features">'+escapeHTML(features.join("، "))+'</p>':'')+'<a class="recommendation-link" href="'+escapeHTML(url)+'" target="_blank" rel="noopener noreferrer">مشاهده کالا</a></article>';}
  function fillForm(profile){if(!profile)return;const d=profile.declared||{};if($("v5Category"))$("v5Category").value=d.category||"";if($("budgetMax"))$("budgetMax").value=d.budget&&d.budget.max?d.budget.max:"";}
  async function renderProfile(profile){const resultSection=$("resultSection"),summary=$("needSummary"),box=$("v6ResultRecommendations"),hint=$("resultHint");if(!resultSection||!summary||!box||!hint)return;summary.className="need-summary empty";summary.textContent="";if(!profile){box.innerHTML="";hint.textContent="برای شروع اطلاعات خریدت رو وارد کن.";resultSection.hidden=true;return;}if(!window.DigiYarNeedEngine){hint.textContent="موتور تحلیل نیاز در دسترس نیست.";resultSection.hidden=false;return;}let need;try{need=window.DigiYarNeedEngine.buildNeedFromProfile(profile);}catch(error){console.error("DigiYar Need Engine:",error);hint.textContent="خطا در ساخت نیاز خرید.";resultSection.hidden=false;return;}resultSection.hidden=false;resultSection.scrollIntoView({behavior:"smooth",block:"start"});hint.textContent="در حال پیدا کردن کالاهای مناسب...";box.innerHTML='<div class="recommendation-loading">در حال جستجوی کالاهای واقعی...</div>';const recommendations=await getRecommendations(need);if(!recommendations.length){box.innerHTML='<div class="need-summary">برای این نیاز هنوز پیشنهاد مناسبی پیدا نشد.</div>';hint.textContent="اطلاعات بیشتری وارد کن تا پیشنهادهای دقیق‌تری ساخته شود.";return;}box.innerHTML=recommendations.map(renderRecommendationCard).join("");hint.textContent="بر اساس اولویت‌های انتخابی تو به ترتیب زیر پیشنهاد میشن";}
  const profileForm=$("profileForm");if(profileForm)profileForm.addEventListener("submit",async function(event){event.preventDefault();if(!window.DigiYarUserProfile)return;try{const profile=window.DigiYarUserProfile.normalize({category:$("v5Category")?$("v5Category").value:"",budgetMax:$("budgetMax")?$("budgetMax").value:"",priorities:"",usage:"",requirements:"",constraints:""});window.DigiYarUserProfile.save(profile);await renderProfile(profile);}catch(error){console.error("DigiYar Profile:",error);}});
  const reset=$("resetProfile");if(reset)reset.addEventListener("click",function(){if(window.DigiYarUserProfile)window.DigiYarUserProfile.clear();if($("profileForm"))$("profileForm").reset();renderProfile(null);});
  let deferredInstallPrompt=null;let installPromptShown=false;let installPromptDismissed=false;let installPromptTimer=null;let installPromptDelayTimer=null;let installPromptHideTimer=null;
  const installPrompt=$("installPrompt"),installBtn=$("installBtn"),installDismiss=$("installDismiss");
  function hideInstallPrompt(){if(!installPrompt)return;window.clearTimeout(installPromptHideTimer);installPrompt.classList.remove("show");installPrompt.classList.add("hiding");installPromptHideTimer=window.setTimeout(function(){installPrompt.classList.add("hidden");installPrompt.classList.remove("hiding");},700);}
  function showInstallPrompt(){if(installPromptShown||installPromptDismissed||!deferredInstallPrompt||!installPrompt)return;window.clearTimeout(installPromptHideTimer);installPromptShown=true;installPrompt.classList.remove("hidden","hiding");requestAnimationFrame(function(){requestAnimationFrame(function(){installPrompt.classList.add("show");});});window.clearTimeout(installPromptTimer);installPromptTimer=window.setTimeout(hideInstallPrompt,9000);}
  const installEligibleAt=Date.now()+8000;
  window.addEventListener("beforeinstallprompt",function(event){event.preventDefault();deferredInstallPrompt=event;window.clearTimeout(installPromptDelayTimer);installPromptDelayTimer=window.setTimeout(showInstallPrompt,Math.max(0,installEligibleAt-Date.now()));});
  if(installBtn)installBtn.addEventListener("click",async function(){if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice;}catch(e){}deferredInstallPrompt=null;window.clearTimeout(installPromptTimer);hideInstallPrompt();});
  if(installDismiss)installDismiss.addEventListener("click",function(){installPromptDismissed=true;window.clearTimeout(installPromptTimer);window.clearTimeout(installPromptDelayTimer);hideInstallPrompt();});
  syncSelectedStoreData();renderStoreSelect();renderPlatforms();let savedProfile=null;if(window.DigiYarUserProfile){try{savedProfile=window.DigiYarUserProfile.getProfile();}catch(error){savedProfile=null;}}fillForm(savedProfile);renderProfile(savedProfile);
  window.addEventListener('resize',syncPopularGridHeight,{passive:true});
})();