/* DigiYar V5 — Steps 3–10 UI orchestration */
(function(){'use strict';const $=id=>document.getElementById(id);
function initDeals(){const track=$('v5DealTrack'),dots=$('v5DealDots'),viewport=$('v5DealViewport');if(!track||!dots||!viewport)return;let index=0,timer=null;const cards=[...track.children].filter(el=>el.classList.contains('v5-deal')),count=cards.length;if(!count)return;const updateDots=()=>{const offsets=[-2,-1,0,1,2];if(dots.children.length!==5){dots.innerHTML='';offsets.forEach(offset=>{const b=document.createElement('button');b.type='button';b.addEventListener('click',()=>{const target=Number(b.dataset.target);if(Number.isInteger(target)){index=target;render();restart()}});dots.appendChild(b)})}Array.from(dots.children).forEach((b,i)=>{const offset=offsets[i],target=(index+offset+count)%count;b.dataset.offset=String(offset);b.dataset.target=String(target);b.setAttribute('aria-label',`اسلاید ${target+1}`);b.classList.toggle('active',offset===0)})};const render=()=>{track.style.transform=`translate3d(${-index*100}%,0,0)`;updateDots()};const next=()=>{index=(index+1)%count;render()};const restart=()=>{clearInterval(timer);timer=setInterval(next,3000)};let startX=0,startY=0,moved=false;viewport.addEventListener('touchstart',e=>{const t=e.changedTouches[0];startX=t.clientX;startY=t.clientY;moved=false;clearInterval(timer)},{passive:true});viewport.addEventListener('touchmove',e=>{const t=e.changedTouches[0];if(Math.abs(t.clientX-startX)>8)moved=true},{passive:true});viewport.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-startX,dy=t.clientY-startY;if(moved&&Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy)){index=(index+(dx<0?1:-1)+count)%count;render()}restart()},{passive:true});addEventListener('resize',render);render();restart()}
function initAffiliateDeals(){document.querySelectorAll('.v5-deal-affiliate').forEach(card=>{const go=()=>{const url=(card.dataset.affiliateUrl||'').trim();if(!url)return;try{const parsed=new URL(url,location.href);if(!/^https?:$/.test(parsed.protocol))return;window.location.href=parsed.href}catch(e){}};card.addEventListener('click',e=>{if(e.target.closest('.v6-store-deal-link'))return;go()});card.addEventListener('keydown',e=>{if(e.target.closest('.v6-store-deal-link'))return;if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})})}function initRevenueTracking(){const key='digiyar-v7-revenue-events';const read=()=>{try{const raw=localStorage.getItem(key);const data=raw?JSON.parse(raw):[];return Array.isArray(data)?data:[]}catch(e){return[]}};const save=data=>{try{localStorage.setItem(key,JSON.stringify(data.slice(-200)))}catch(e){}};const track=(store,url,source)=>{const event={type:'affiliate_click',store:String(store||'unknown'),source:String(source||'unknown'),timestamp:new Date().toISOString(),url:String(url||'')};const data=read();data.push(event);save(data);try{window.dispatchEvent(new CustomEvent('digiyar:affiliate-click',{detail:event}))}catch(e){}};document.querySelectorAll('[data-affiliate-url]').forEach(el=>{if(el.dataset.revenueTracked==='1')return;el.dataset.revenueTracked='1';el.addEventListener('click',function(e){const link=e.target.closest('a[data-affiliate-url],.v6-store-deal-link');const url=(link&&link.getAttribute('href'))||el.dataset.affiliateUrl||'';if(!url)return;track(el.dataset.store||el.getAttribute('data-store'),url,el.classList.contains('v6-store-deal')?'deal':'affiliate')},{capture:true})});window.DigiYarRevenue={getEvents:read,clear:function(){try{localStorage.removeItem(key)}catch(e){}}};}
function initHeader(){const brand=$('v5HeaderBrand'),tag=$('v5HeaderTagline');if(!brand||!tag)return;const states=[['دیجی‌یار','دستیار هوشمند خرید اینترنتی تو'],['دیجی‌یار','دنبال بهترین انتخابی؟ با دیجی‌یار پیداش کن'],['دیجی‌یار','قبل از خرید، هوشمندانه انتخاب کن']];let i=0;const apply=()=>{const s=states[i++%states.length];brand.textContent=s[0];tag.textContent=s[1]};apply();setInterval(apply,4800)}
function moveRecommendations(){const result=$('resultSection'),target=$('v5InlineResults'),rec=$('recommendations');if(result&&target&&rec){target.appendChild(rec);result.classList.add('v5-result-card')}}
function initChat(){const form=$('digiyar-chat-form'),btn=form?.querySelector('button');if(btn){btn.setAttribute('aria-label','ارسال پیام');btn.innerHTML='<svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true"><path d="M21 3 9.4 14.6M21 3l-7.4 18-4.2-6.4L3 10.4 21 3Z" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'}}
function initProfileSave(){const form=$('v5ProfileCompletionForm');if(!form)return;const status=$('v5ProfileSaveStatus');form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());localStorage.setItem('digiyar-v5-profile',JSON.stringify(data));if(status){status.textContent='پروفایل ذخیره شد؛ خبرهای جذاب را بر اساس آن برایت آماده می‌کنیم.';setTimeout(()=>status.textContent='',3000)}})}
function initProfileCompletionToggle(){const card=document.querySelector('.v5-profile-completion,.v5-profile-card');const form=$('v5ProfileCompletionForm')||$('profileForm');if(!card||!form)return;const existing=card.querySelector('.v5-profile-completion-toggle,.v5-step4-final-toggle');if(existing)existing.remove();const toggle=document.createElement('button');toggle.type='button';toggle.className='v5-step4-toggle v5-profile-completion-toggle v5-step4-final-toggle';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','باز کردن تکمیل پروفایل');toggle.innerHTML='<span class="v5-step4-toggle-icon v5-profile-completion-toggle-icon" aria-hidden="true"><i>⟨</i><i>⟨</i><i>⟨</i></span>';card.appendChild(toggle);const setState=open=>{card.classList.toggle('is-open',open);form.hidden=!open;form.setAttribute('aria-hidden',String(!open));form.style.display=open?'grid':'';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'بستن تکمیل پروفایل':'باز کردن تکمیل پروفایل')};toggle.addEventListener('click',()=>setState(toggle.getAttribute('aria-expanded')!=='true'));setState(false)}
function initProfileCompletionFields(){const form=$('v5ProfileCompletionForm');if(!form)return;form.querySelectorAll('label').forEach(label=>{const field=label.querySelector('input,select,textarea');if(!field)return;const text=[...label.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent.trim()).filter(Boolean).join(' ').trim();if(text&&!field.getAttribute('placeholder'))field.setAttribute('placeholder',text);[...label.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).forEach(n=>n.remove());label.removeAttribute('aria-hidden')})}
function removeTemporaryAIConversation(){const card=$('digiyarConversation');if(card)card.remove()}
function initPopularStores(){const card=document.querySelector('.v5-popular-card');const grid=$('platforms');if(!card||!grid)return;const existing=card.querySelector('.v5-popular-toggle');if(existing)existing.remove();const toggle=document.createElement('button');toggle.type='button';toggle.className='v5-popular-toggle';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','باز کردن فروشگاه‌های محبوب');toggle.innerHTML='<span class="v5-popular-toggle-icon" aria-hidden="true"><i>⟨</i><i>⟨</i><i>⟨</i></span>';card.appendChild(toggle);const setState=open=>{card.classList.toggle('is-open',open);grid.hidden=!open;grid.setAttribute('aria-hidden',String(!open));toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'بستن فروشگاه‌های محبوب':'باز کردن فروشگاه‌های محبوب')};toggle.addEventListener('click',()=>setState(toggle.getAttribute('aria-expanded')!=='true'));const links=['https://aflo.ir/16da7m1UY','https://aflo.ir/YPN05dL7','https://torob.com/','https://basalam.com/'];Array.from(grid.querySelectorAll('.platform')).forEach((el,i)=>{if(links[i]){el.setAttribute('href',links[i]);el.setAttribute('data-affiliate-url',links[i]);}el.setAttribute('target','_blank');el.setAttribute('rel','noopener noreferrer')});setState(false)}
function initPageHarmony(){const popular=document.querySelector('.v5-popular-card');if(popular){const title=popular.querySelector('.section-title');if(title&&!title.querySelector('.v5-card-subtitle')){const p=document.createElement('p');p.className='v5-card-subtitle';p.textContent='دنبال هر چی هستی، خودت از فروشگاه محبوبت پیداش کن';title.appendChild(p)}}if(!document.querySelector('link[data-v5-page-harmony]')){const link=document.createElement('link');link.rel='stylesheet';link.href='css/v5-page-harmony.css';link.dataset.v5PageHarmony='true';document.head.appendChild(link)}}
function initFooterNavigation(){
if(document.getElementById('v6FooterNav'))return;
const popular=document.querySelector('.v5-popular-card');
const profileCard=document.querySelector('.v5-profile-card.profile-card');
const profileCompletionCard=document.querySelector('.v5-profile-completion');
const deals=document.getElementById('v7DealsHost');
const style=document.createElement('style');
style.id='v6-footer-navigation-style';
style.textContent='.v6-footer-nav{position:fixed;left:0;right:0;bottom:0;z-index:9999;height:68px;padding:7px 10px;box-sizing:border-box;display:grid;grid-template-columns:repeat(5,1fr);align-items:center;direction:rtl;background:#fff;border-top:1px solid #dfe6f0;box-shadow:0 -8px 24px rgba(16,28,53,.12)}.v6-footer-nav button{min-width:0;height:54px;border:0;background:transparent;color:#69778d;display:flex;flex-direction:column;align-items:center;justify-content:center;cursor:pointer}.v6-footer-nav button svg{display:block!important;visibility:visible!important;opacity:1!important;width:24px;height:24px;flex:0 0 24px;overflow:visible}.v6-footer-nav button[data-v6-action="recommendations"] svg{color:#f5c400;transform-origin:center;animation:v7StarAttention 3.6s ease-in-out infinite}@keyframes v7StarAttention{0%,55%,100%{transform:scale(1)}72%{transform:scale(2)}82%{transform:scale(1)}}@media(prefers-reduced-motion:reduce){.v6-footer-nav button[data-v6-action="recommendations"] svg{animation:none}}.v6-footer-nav button span{display:none!important}.v6-footer-nav .v6-menu{width:50px;height:50px;justify-self:center;border-radius:15px;background:#2a4169;color:#fff}.v6-nav-sheet{position:fixed;left:12px;right:12px;bottom:76px;z-index:10000;max-height:68vh;overflow:auto;padding:11px;border:1px solid #dfe6f0;border-radius:18px;background:#fff;box-shadow:0 16px 42px rgba(16,28,53,.2);direction:rtl;display:none}.v6-nav-sheet.is-open{display:block}.v6-sheet-grid{display:grid;grid-template-columns:1fr;gap:8px}.v6-sheet-action{min-height:50px;padding:9px;border:1px solid #dfe6f0;border-radius:12px;background:#f8fafd;color:#2a4169}.v6-nav-backdrop{position:fixed;inset:0;z-index:9998;background:rgba(16,28,53,.24);display:none}.v6-nav-backdrop.is-open{display:block}.v6-menu-profile-card,.v6-menu-popular-card,.v6-menu-profile-completion-card,.v6-menu-deals-card{display:block!important;width:100%!important;margin:0!important;padding:11px!important;box-sizing:border-box!important}.v6-nav-sheet .section-title,.v6-nav-sheet .v5-section-heading{display:block!important;position:sticky!important;top:-11px!important;z-index:30!important;background:#fff!important;padding:11px 0 8px!important;margin:-11px 0 8px!important;border-bottom:1px solid #edf1f6!important}.v6-nav-sheet .section-title h2,.v6-nav-sheet .v5-section-heading h2{margin:0!important;text-align:center!important}.v6-nav-sheet .section-title p,.v6-nav-sheet .v5-section-heading p{display:block!important;margin:3px 0 0!important;text-align:center!important}.v6-nav-sheet .v5-popular-toggle,.v6-nav-sheet .v5-profile-completion-toggle,.v6-nav-sheet .v5-step4-final-toggle{display:none!important}.v6-menu-popular-card .platform-grid{height:auto!important;max-height:none!important;overflow:visible!important}.v6-nav-sheet .v5-deal-viewport{width:100%!important}';
document.head.appendChild(style);
const nav=document.createElement('nav');
nav.id='v6FooterNav';nav.className='v6-footer-nav';nav.setAttribute('aria-label','ناوبری اصلی');
nav.innerHTML='<button type="button" data-v6-action="account" aria-label="حساب من"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5" fill="none" stroke="currentColor" stroke-width="2"/><path d="M5 21c.7-4 3.1-6 7-6s6.3 2 7 6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><span>حساب من</span></button><button type="button" data-v6-action="recommendations" aria-label="پیشنهادها"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2.5 2.93 5.94 6.56.95-4.74 4.62 1.12 6.53L12 17.46l-5.87 3.08 1.12-6.53-4.74-4.62 6.56-.95L12 2.5Z" fill="currentColor"/></svg><span>پیشنهادها</span></button><button type="button" class="v6-menu" data-v6-action="menu" aria-label="منوی اصلی"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><span>☰</span></button><button type="button" data-v6-action="search" aria-label="جستجو"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" fill="none" stroke="currentColor" stroke-width="2"/><path d="m16 16 5 5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><span>جستجو</span></button><button type="button" data-v6-action="home" aria-label="خانه"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 11 9-7 9 7" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M5.5 10.5V21h13V10.5M9 21v-6h6v6" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg><span>خانه</span></button>';
document.body.appendChild(nav);
const backdrop=document.createElement('div');backdrop.className='v6-nav-backdrop';document.body.appendChild(backdrop);
const sheet=document.createElement('section');sheet.className='v6-nav-sheet';sheet.innerHTML='<div id="v6SheetBody"></div>';document.body.appendChild(sheet);
const body=sheet.querySelector('#v6SheetBody');
const anchors=new Map();
[popular,profileCard,profileCompletionCard,deals].forEach(card=>{if(card&&card.parentNode){const a=document.createComment('v7-nav-anchor-'+card.id);card.parentNode.insertBefore(a,card);anchors.set(card,a);}});
let activeCard=null;
const restoreCard=card=>{
if(!card)return;
const a=anchors.get(card);if(a&&a.parentNode)a.parentNode.insertBefore(card,a.nextSibling);
card.hidden=true;card.setAttribute('aria-hidden','true');
card.classList.remove('is-open','v6-menu-profile-card','v6-menu-popular-card','v6-menu-profile-completion-card','v6-menu-deals-card');
const form=card.querySelector('form');if(form){form.hidden=true;form.setAttribute('aria-hidden','true');form.style.display='';}
const grid=card.querySelector('#platforms');if(grid){grid.hidden=true;grid.setAttribute('aria-hidden','true');}
};
const close=()=>{restoreCard(activeCard);activeCard=null;body.innerHTML='';sheet.classList.remove('is-open');backdrop.classList.remove('is-open');};
const showCard=(card,title,cls)=>{
if(!card)return;
if(activeCard===card){close();return;}
if(activeCard)restoreCard(activeCard);
activeCard=card;card.hidden=false;card.removeAttribute('aria-hidden');card.classList.add('is-open',cls);
const form=card.querySelector('form');if(form){form.hidden=false;form.removeAttribute('aria-hidden');form.style.display='grid';}
const grid=card.querySelector('#platforms');if(grid){grid.hidden=false;grid.removeAttribute('aria-hidden');}
body.innerHTML='';body.appendChild(card);sheet.classList.add('is-open');backdrop.classList.add('is-open');
};
window.__v7OpenDeals=()=>{if(deals)showCard(deals,'پیشنهادات','v6-menu-deals-card');return !!deals;};const openRoot=()=>{if(sheet.classList.contains('is-open')){close();return;}body.innerHTML='<div class="v6-sheet-grid"><button class="v6-sheet-action" type="button" data-v6-profile>دنبال چی می‌گردی؟</button><button class="v6-sheet-action" type="button" data-v6-popular>فروشگاه‌های محبوب</button><button class="v6-sheet-action" type="button" data-scroll="footerPanels">اطلاعات و راهنما</button></div>';sheet.classList.add('is-open');backdrop.classList.add('is-open');};
backdrop.addEventListener('click',close);
sheet.addEventListener('click',e=>{
const profile=e.target.closest('[data-v6-profile]'),popularBtn=e.target.closest('[data-v6-popular]'),dealsBtn=e.target.closest('[data-v6-deals]'),scrollBtn=e.target.closest('[data-scroll]');
if(profile)showCard(profileCard,'دنبال چی می‌گردی؟','v6-menu-profile-card');
else if(popularBtn)showCard(popular,'فروشگاه‌های محبوب','v6-menu-popular-card');
else if(dealsBtn)showCard(deals,'پیشنهادات','v6-menu-deals-card');
else if(scrollBtn){const target=$(scrollBtn.dataset.scroll);close();if(target)target.scrollIntoView({behavior:'smooth',block:'start'});}
});
nav.querySelectorAll('button[data-v6-action]').forEach(button=>button.addEventListener('click',()=>{
const action=button.dataset.v6Action;
if(action==='menu')openRoot();
else if(action==='account')showCard(profileCompletionCard,'تکمیل و ویرایش پروفایل','v6-menu-profile-completion-card');
else if(action==='recommendations'){const target=$('recommendations')||$('v5InlineResults');if(target)target.scrollIntoView({behavior:'smooth',block:'start'});}
else if(action==='search'){const target=$('v5SmartSearchInput');if(target){target.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>target.focus(),350);}}
else if(action==='home'){close();window.scrollTo({top:0,behavior:'smooth'});}
}));
}
function initRevenueTestPanel(){if(new URLSearchParams(location.search).get('revenue-test')!=='1')return;if(document.getElementById('v7RevenueTestPanel'))return;const wrap=document.createElement('section');wrap.id='v7RevenueTestPanel';wrap.dir='rtl';wrap.style.cssText='position:fixed;inset:10px;z-index:20000;max-height:calc(100vh - 20px);overflow:auto;padding:16px;border:2px solid #2a4169;border-radius:16px;background:#fff;color:#18243a;box-shadow:0 20px 60px rgba(0,0,0,.3);font-family:inherit';const render=()=>{let events=[];try{events=window.DigiYarRevenue?.getEvents?.()||[]}catch(e){};wrap.innerHTML='<div style="display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px"><strong style="font-size:18px">تست Tracking دیجی‌یار</strong><button id="v7RevenueTestClose" type="button" style="border:0;background:#eee;border-radius:10px;padding:8px 12px;font-size:18px">×</button></div><div style="margin-bottom:12px">تعداد Eventهای ثبت‌شده: <strong>'+events.length+'</strong></div>'+(events.length?events.slice().reverse().map((e,i)=>'<article style="padding:10px;margin:8px 0;border:1px solid #dfe6f0;border-radius:10px"><strong>#'+(events.length-i)+'</strong><div>فروشگاه: '+String(e.store||'-')+'</div><div>نوع: '+String(e.type||'-')+'</div><div>منبع: '+String(e.source||'-')+'</div><div>زمان: '+String(e.timestamp||'-')+'</div><div style="word-break:break-all">URL: '+String(e.url||'-')+'</div></article>').join(''):'<p>هنوز هیچ Eventای ثبت نشده است.</p>')+'<div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button id="v7RevenueTestRefresh" type="button" style="padding:9px 12px;border:1px solid #2a4169;border-radius:10px;background:#f8fafd">به‌روزرسانی</button><button id="v7RevenueTestClear" type="button" style="padding:9px 12px;border:1px solid #c33;border-radius:10px;background:#fff;color:#b22">پاک کردن Eventها</button></div>';wrap.querySelector('#v7RevenueTestClose').onclick=()=>wrap.remove();wrap.querySelector('#v7RevenueTestRefresh').onclick=render;wrap.querySelector('#v7RevenueTestClear').onclick=()=>{window.DigiYarRevenue?.clear?.();render()};};document.body.appendChild(wrap);render()}
function init(){initFooterNavigation();initRevenueTestPanel();initDeals();initAffiliateDeals();initRevenueTracking();initHeader();moveRecommendations();initChat();initProfileSave();removeTemporaryAIConversation();initProfileCompletionFields();initPageHarmony()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();