/* DigiYar V6 Worker — force redeploy of current live resolver contract (2026-09-14) */
import { ingestCategory } from './js/data-ingestion-v5.1.js';
import { PRODUCT_INDEX, INDEX_META } from './js/product-index-generated-v5.1.js';
import { resolveProduct } from './js/v5-price-availability-resolver.js';
import { normalizeCurrency, toToman } from './js/v5-price-contract.mjs';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, OPTIONS','Access-Control-Allow-Headers':'Content-Type'};
const STORES={digikala:{id:'digikala',name:'دیجی‌کالا',affiliate:'https://aflo.ir/TrvNHEN8'},snappshop:{id:'snappshop',name:'اسنپ‌شاپ',affiliate:'https://aflo.ir/YPN05dL7'}};
const norm=s=>String(s??'').toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[٬,]/g,'').replace(/\s+/g,' ').trim();
const STOP=new Set(['برای','با','و','در','از','یک','این','آن','می','به','تومان','تومن','میلیون','میلیارد','هزار','تا','یه','دنبال','میگردم','می‌گردم','میخوام','می‌خوام','میخواهم','می‌خواهم','لطفا','لطفاً','میشه','می‌شود','هستم','هست','رو','را']);
const money=(n,u='')=>{const x=Number(n);if(!Number.isFinite(x))return 0;return !u||u==='تومان'||u==='تومن'?x:u==='هزار'?x*1e3:u==='میلیون'?x*1e6:u==='میلیارد'?x*1e9:x};
const PRODUCT_TYPES={phone:['گوشی','موبایل','موبايل'],laptop:['لپ','تاپ','لپتاپ']};
function parseQ(q=''){const n=norm(q),t=n.split(' ').filter(Boolean),brands=['سامسونگ','شیائومی','اپل','آیفون','هواوی','آنر','لنوو','ایسوس','اچ‌پی','hp','dell','acer','msi','مایکروسافت'].filter(b=>n.includes(b)),range=n.match(/(\d+(?:\.\d+)?)\s*(?:تا|-|–)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان|تومن)?/i),max=n.match(/(?:زیر|کمتر از|حداکثر|تا)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان|تومن)?/i),min=n.match(/(?:بالای|بیشتر از|حداقل)\s*(\d+(?:\.\d+)?)\s*(میلیون|میلیارد|هزار|تومان|تومن)?/i);const price=range?{minPrice:money(range[1],range[3]),maxPrice:money(range[2],range[3])}:{minPrice:min?money(min[1],min[2]):null,maxPrice:max?money(max[1],max[2]):null};return{normalized:n,tokens:t,brands,price:{...price,currency:'TOMAN'},keywords:t.filter(x=>!STOP.has(x)&&!/^[0-9.]+$/.test(x))}};
function valid(p){if(!p?.productId||!p?.productUrl)return false;try{return/^https?:$/.test(new URL(p.productUrl).protocol)&&!/\/search(?:\/|\?|$)/i.test(new URL(p.productUrl).pathname)}catch{return false}}
function affiliate(store,url){const b=STORES[store]?.affiliate;return b&&url?`${b}?p=${encodeURIComponent(url)}`:''}
function priceToman(o){if(Number(o?.priceToman)>0)return Math.round(Number(o.priceToman));return toToman(o?.price,normalizeCurrency(o?.currency||'IRT'))}
function searchableText(o){return norm([o.name,o.productName,o.brand,o.model,o.category,o.subcategory].filter(Boolean).join(' '))}
function relevant(o,z){const text=searchableText(o),name=norm(o.name||'');if(z.brands.length&&!z.brands.some(b=>text.includes(norm(b))))return false;const hasPhone=z.keywords.some(w=>PRODUCT_TYPES.phone.includes(w)),hasLaptop=z.keywords.some(w=>PRODUCT_TYPES.laptop.includes(w));if(hasPhone&&!/گوشی|موبایل|موبايل/.test(name))return false;if(hasLaptop&&!(/لپ\s*تاپ|لپتاپ/.test(name)||norm(o.category)==='laptop-computer'||norm(o.subcategory)==='لپ تاپ'))return false;return true}
function rank(items,q){const z=parseQ(q);return items.filter(valid).filter(o=>{const p=priceToman(o);return(z.price.minPrice==null||p>=z.price.minPrice)&&(z.price.maxPrice==null||p<=z.price.maxPrice)&&(z.price.minPrice==null&&z.price.maxPrice==null||p>0)}).filter(o=>relevant(o,z)).map(o=>{const n=searchableText(o),score=z.keywords.reduce((s,w)=>s+(n.includes(norm(w))?12:0),0)+(z.brands.some(b=>n.includes(norm(b)))?40:0)+(o.availability==='in_stock'?8:0)+(priceToman(o)>0?3:0)+(o.productUrl?10:0);return{...o,priceToman:priceToman(o),priceUnit:'toman',score}}).sort((a,b)=>b.score-a.score||(a.priceToman||Infinity)-(b.priceToman||Infinity))}
function dedupe(items=[]){const seen=new Set();return items.filter(o=>{const key=String(o.productUrl||o.productId||o.id||'').trim();if(!key||seen.has(key))return false;seen.add(key);return true})}
function localSearch(q){const results=rank(dedupe(PRODUCT_INDEX.map(p=>({...p,productId:p.productId||p.id,productName:p.name,storeId:p.storeId||p.sourceId,storeName:p.storeName||p.sourceId,affiliateUrl:p.affiliateUrl||''}))),q);return{results,source:'local-product-index',indexSize:PRODUCT_INDEX.length}}
async function req(url,accept){const r=await fetch(url,{redirect:'follow',headers:{Accept:accept,'Accept-Language':'fa-IR,fa;q=0.9,en;q=0.8','User-Agent':'Mozilla/5.0 (compatible; DigiYar/5.1)'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r}
async function dk(q){for(const base of ['https://api.digikala.com/v1/search/','https://api.digikala.com/v2/search/']){try{const r=await req(`${base}?q=${encodeURIComponent(q)}&page=1`,'application/json'),d=await r.json(),p=d?.data?.products||d?.data?.data?.products||[];if(p.length)return p.slice(0,10).map(x=>{const id=x?.id||x?.product_id||x?.product?.id,url=id?`https://www.digikala.com/product/dkp-${id}/`:'';const price=x?.default_variant?.price?.selling_price??x?.price?.selling_price??0;return{productId:String(id||''),name:x?.title_fa||x?.title_en||'',price:Number(String(price).replace(/,/g,''))||0,currency:'IRR',priceToman:toToman(price,'IRR'),availability:id?'in_stock':'unknown',productUrl:url,affiliateUrl:affiliate('digikala',url),storeId:'digikala',storeName:STORES.digikala.name,source:'digikala-api'}})}catch{}}return[]}
async function ss(q){try{const r=await req(`https://snappshop.ir/search?q=${encodeURIComponent(q)}`,'text/html,application/xhtml+xml,application/json'),h=await r.text(),out=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(h))){try{walk(JSON.parse(m[1]),out)}catch{}}return out.map(x=>{const url=x.productUrl||x.url||'',id=String(x.productId||x.sku||x.productID||'');return{productId:id,name:x.name||x.productName||'',price:Number(x.price||0),currency:x.currency||'IRT',priceToman:toToman(x.price,x.currency||'IRT'),availability:x.available===false?'out_of_stock':'in_stock',productUrl:url,affiliateUrl:affiliate('snappshop',url),storeId:'snappshop',storeName:STORES.snappshop.name,source:'snappshop-jsonld'}})}catch{return[]}}
function walk(x,out){if(!x)return;if(Array.isArray(x)){x.forEach(v=>walk(v,out));return}if(typeof x!=='object')return;const t=String(x['@type']||'').toLowerCase();if(t.includes('product')&&(x.url||x.sku||x.productID)){const o=Array.isArray(x.offers)?x.offers[0]:x.offers||{};out.push({productId:x.sku||x.productID||x.mpn||'',name:x.name||'',productUrl:x.url||'',price:o.price||0,currency:o.priceCurrency||'IRT',available:o.availability?!/outofstock/i.test(o.availability):true})}Object.values(x).forEach(v=>v&&typeof v==='object'&&walk(v,out))}
export default{async fetch(request){if(request.method==='OPTIONS')return new Response(null,{headers:CORS});const u=new URL(request.url),q=(u.searchParams.get('q')||'').trim();if(u.pathname==='/health')return json({status:'ok',version:'v5.1-search-core',priceContract:'5.1.0:TOMAN',ingestion:true,index:'web-product-catalog',indexSize:PRODUCT_INDEX.length,meta:INDEX_META});if(u.pathname==='/api/catalog')return json({success:true,version:'v5.1-catalog',indexSize:PRODUCT_INDEX.length,meta:INDEX_META,categories:{mobile:PRODUCT_INDEX.filter(x=>x.category==='mobile').length,laptop:PRODUCT_INDEX.filter(x=>x.category==='laptop').length}});if(u.pathname==='/api/ingest'){if(!q)return json({success:false,error:'Missing q'});try{const data=await ingestCategory(q);return json({success:true,version:'v5.1-ingestion',query:q,items:data.items,total:data.items.length,stores:data.sources,generatedAt:data.generatedAt})}catch(e){return json({success:false,query:q,items:[],total:0,error:String(e)})}}if(u.pathname==='/api/resolve'){const productUrl=(u.searchParams.get('url')||'').trim();if(!productUrl)return json({success:false,error:'Missing url'});try{const result=await resolveProduct(productUrl);return json({...result,resolverVersion:'5.1.1-live-resolver'});}catch(e){return json({success:false,resolved:false,error:String(e),productUrl,resolverVersion:'5.1.1-live-resolver'})}}if(u.pathname!=='/api/search')return json({error:'Unknown endpoint'});if(!q)return json({success:false,results:[],total:0,error:'Missing q'});const live=await Promise.allSettled([dk(q),ss(q)]),liveRaw=dedupe(live.flatMap(x=>x.status==='fulfilled'?x.value:[]));let results=rank(liveRaw,q);let source='live-store-search',ingestion=null;if(!results.length){try{ingestion=await ingestCategory(q);const ingested=dedupe(Array.isArray(ingestion.items)?ingestion.items:[]);results=rank(ingested,q);if(results.length)source='live-ingestion-fallback'}catch{results=[]}if(!results.length){const local=localSearch(q);results=local.results;source='local-web-catalog'}}results=results.slice(0,20);return json({success:true,version:'v5.1',query:q,parsed:parseQ(q),results,total:results.length,source,indexSize:PRODUCT_INDEX.length,sources:{digikala:live[0].status==='fulfilled'?(live[0].value.length?'fulfilled':'fulfilled_empty'):'rejected',snappshop:live[1].status==='fulfilled'?(live[1].value.length?'fulfilled':'fulfilled_empty'):'rejected'},ingestion:ingestion?{digikala:ingestion.sources.digikala.status,snappshop:ingestion.sources.snappshop.status}:null})}};
function json(x){return new Response(JSON.stringify(x),{headers:{...CORS,'Content-Type':'application/json'}})}
